### ISSUE TITLE
undefined function sympositivedefinitefactory

### ISSUE THREAD

**Issue by pribadihcr** [mfaraki/Riemannian_VLAD#1]
Hi @mfaraki 

I got the following error:
Undefined function 'sympositivedefinitefactory' for input arguments of type 'double'.
many thanks

**Comment by mfaraki** [comment]
Hi @pribadihcr ,
Please install the [Manopt](http://www.manopt.org/) toolbox first.

**Comment by pribadihcr** [comment]
Hi @mfaraki 

Yes, I did, and it worked. I forgot to install it. 
Thanks
